// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UptimeMonitor.Api.Models;

#nullable disable

namespace UptimeMonitor.Api.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20250815162134_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("UptimeMonitor.Api.Models.CheckLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonitorTargetId", "CheckedAt");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("UptimeMonitor.Api.Models.MonitorTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFails")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSec")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.ToTable("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
